version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp-backend
    container_name: myapp-node-backend
    command: npm run start
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: ./backend/.env.dev
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo:latest
    # environment:  // If Mongo Authorization is need to be enabled
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myapp-frontend
    container_name: myapp-react-frontend
    command: npm run start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
